---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: external-http-nginx-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: external-http-nginx-service
  annotations:
    service.beta.kubernetes.io/vra-internet-facing-load-balancer: "true"
    loadbalancer.vmware.com/floating-network-id: "9be23551-38e2-4d27-b5ea-ea2ea1321bd6"
spec:
  selector:
    app: nginx
  type: LoadBalancer

  ports:
  - name: http
    port: 80
    targetPort: 80

  routes:
    protocol: HTTP
    port: 80
    memberProtocol: HTTP
    memberPort: HTTP
    healthCheckConfiguration:
      protocol: HTTP
      port: 80
      urlPath: /index.html
      intervalSeconds: 60
      timeoutSeconds: 5
      unhealthyThreshold: 2
      healthyThreshold: 2

  nics: 
    name: xtests
    description: for_testing
    deviceIndex: 1
    networkId: 
    addresses: 
    securityGroupIds: 

  internetFacing: true
  targetLinks: 
